
name: "  Run Tests on Godot 3.3  "

on: [push, pull_request]

jobs:
  Tests:
    name: Run All Tests on 3.3
    runs-on:  ubuntu-latest
    container: barichello/godot-ci:mono-3.3
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug
      - name: Compile
        run: msbuild
      - name: Reimport Assets
        run: godot --editor addons/WAT/rebuild_and_close.tscn
        timeout-minutes: 1
      - name: Run
        run: godot addons/WAT/cli.tscn -run_all
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: wat_tests/results/results.xml
